name: PermissionMessages
main: org.fatecrafters.plugins.PermissionMessages
version: 2.0
author: Slayr288
website: http://Fatecrafters.org
description: Send timed messages based on permissions.
commands:
  permissionmessages:
    description: Main commands.
    aliases: [pm, permmsg, permmsgs, permissionmsgs]
permissions:
  permissionmessages.reload:
    default: op
  permissionmessages.create:
    default: op
  permissionmessages.add:
    default: op
  permissionmessages.remove:
    default: op
  permissionmessages.list:
    default: op
  permissionmessages.help:
    default: op
  permissionmessages.silence:
    default: false